import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("platform_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="✦", max_length=24)),
                ("active", models.BooleanField(default=True)),
                ("is_medical_reward", models.BooleanField(default=False, editable=False)),
            ],
            options={"verbose_name": "Achievement", "verbose_name_plural": "Achievements", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="BeautyEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=220)),
                ("capacity", models.PositiveIntegerField(default=20)),
                ("allow_guest", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("medical_service_reward", models.BooleanField(default=False, editable=False)),
            ],
            options={"verbose_name": "A+ Event", "verbose_name_plural": "A+ Events", "ordering": ["starts_at", "title"]},
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("challenge_type", models.CharField(choices=[("care", "Pflegeroutine"), ("learning", "Lernen"), ("profile", "Profil"), ("seasonal", "Saisonal"), ("community", "Community")], max_length=20)),
                ("target_count", models.PositiveIntegerField(default=1)),
                ("reward_coins", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("medical_treatment_count_based", models.BooleanField(default=False, editable=False)),
                ("badge", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="challenges", to="p3_app.badge")),
            ],
            options={"ordering": ["ends_at", "title"]},
        ),
        migrations.CreateModel(
            name="ConciergeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_type", models.CharField(choices=[("priority_booking", "Priority Booking"), ("travel_coordination", "Terminabstimmung für Reise"), ("companion", "Termin für Begleitperson"), ("event_support", "Event-Support"), ("product_pickup", "Produktabholung"), ("accessibility", "Barrierefreiheit / Unterstützung"), ("other", "Sonstiges")], max_length=24)),
                ("title", models.CharField(max_length=180)),
                ("details", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Offen"), ("in_progress", "In Bearbeitung"), ("waiting_customer", "Rückfrage an Kunde"), ("completed", "Abgeschlossen"), ("declined", "Nicht verfügbar")], default="open", max_length=20)),
                ("staff_note", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("medical_decision_support", models.BooleanField(default=False, editable=False)),
                ("thread", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="p3_concierge", to="platform_app.thread")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="p3_concierge_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Concierge-Anfrage", "verbose_name_plural": "Concierge-Anfragen", "ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guest_name", models.CharField(blank=True, max_length=120)),
                ("seat_count", models.PositiveSmallIntegerField(default=1)),
                ("status", models.CharField(choices=[("registered", "Angemeldet"), ("waitlist", "Warteliste"), ("cancelled", "Storniert"), ("attended", "Teilgenommen")], default="registered", max_length=15)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="p3_app.beautyevent")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="p3_event_registrations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("passing_percent", models.PositiveSmallIntegerField(default=70)),
                ("reward_coins", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("approved", models.BooleanField(default=False)),
                ("medical_advice", models.BooleanField(default=False, editable=False)),
                ("badge", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quizzes", to="p3_app.badge")),
            ],
            options={"ordering": ["title"]},
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answers", models.JSONField(default=list)),
                ("score", models.PositiveIntegerField(default=0)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("percent", models.PositiveSmallIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("passed", models.BooleanField(default=False)),
                ("reward_granted", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("quiz", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="p3_app.quiz")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="p3_quiz_attempts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("correct_index", models.PositiveSmallIntegerField()),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("quiz", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="p3_app.quiz")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="ChallengeParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("progress", models.PositiveIntegerField(default=0)),
                ("last_progress_on", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reward_granted", models.BooleanField(default=False)),
                ("challenge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participations", to="p3_app.challenge")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="p3_challenge_participations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(blank=True, max_length=30)),
                ("source_id", models.CharField(blank=True, max_length=80)),
                ("badge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="awards", to="p3_app.badge")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="p3_badges", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(model_name="eventregistration", constraint=models.UniqueConstraint(fields=("event", "user"), name="p3_unique_event_registration")),
        migrations.AddConstraint(model_name="quizattempt", constraint=models.UniqueConstraint(fields=("user", "quiz"), name="p3_unique_quiz_attempt")),
        migrations.AddConstraint(model_name="challengeparticipation", constraint=models.UniqueConstraint(fields=("user", "challenge"), name="p3_unique_challenge_participation")),
        migrations.AddConstraint(model_name="userbadge", constraint=models.UniqueConstraint(fields=("user", "badge"), name="p3_unique_user_badge")),
    ]
