from django.urls import path

from . import views

app_name = "experience"

urlpatterns = [
    path("manifest.json", views.manifest_v2, name="manifest"),
    path("sw.js", views.service_worker_v2, name="service_worker"),
    path("mitgliedskarte/qr.png", views.member_qr_v2, name="member_qr"),
    path("mitgliedschaft/", views.member_center, name="member_center"),
    path("mitgliedschaft/apple-wallet/", views.apple_wallet_pass, name="apple_wallet_pass"),
    path("mitgliedschaft/google-wallet/", views.google_wallet_pass, name="google_wallet_pass"),
    path("wallet/", views.wallet_center, name="wallet_center"),
    path("wallet/reward/<int:reward_id>/", views.redeem_reward_action, name="redeem_reward"),
    path("wallet/gift-card/", views.create_giftcard, name="create_giftcard"),
    path("termine/", views.booking_calendar, name="booking_calendar"),
    path("termine/buchen/", views.book_slot, name="book_slot"),
    path("termine/<int:appointment_id>/aendern/", views.appointment_change, name="appointment_change"),
    path("termine/<int:appointment_id>/kalender.ics", views.appointment_ical, name="appointment_ical"),
    path("check-in/<str:token>/", views.checkin_token, name="checkin_token"),
    path("fotos/", views.photo_center, name="photo_center"),
    path("fotos/album/<int:album_id>/upload/", views.upload_photo, name="upload_photo"),
    path("fotos/<int:photo_id>/", views.protected_progress_photo, name="protected_progress_photo"),
    path("nachsorge/", views.aftercare_center, name="aftercare_center"),
    path("nachsorge/aufgabe/<int:status_id>/", views.toggle_aftercare_task, name="toggle_aftercare_task"),
    path("nachsorge/follow-up/<int:followup_id>/", views.respond_followup, name="respond_followup"),
    path("beauty-plan/", views.beauty_plans, name="beauty_plans"),
    path("beauty-plan/schritt/<int:step_id>/", views.toggle_plan_step, name="toggle_plan_step"),
    path("wissensassistent/", views.assistant, name="assistant"),
    path("beauty-cabinet/", views.cabinet, name="cabinet"),
    path("beauty-cabinet/<int:product_id>/entfernen/", views.remove_cabinet_product, name="remove_cabinet_product"),
    path("shop/", views.shop, name="shop"),
    path("shop/<int:product_id>/hinzufuegen/", views.cart_add, name="cart_add"),
    path("shop/checkout/", views.checkout, name="checkout"),
    path("challenges/", views.gamification, name="gamification"),
    path("challenges/<int:challenge_id>/start/", views.join_challenge, name="join_challenge"),
    path("challenges/<int:challenge_id>/fortschritt/", views.challenge_progress, name="challenge_progress"),
    path("kontakt/", views.communication_center, name="communication_center"),
    path("angebote-events/", views.offers_events, name="offers_events"),
    path("events/<int:event_id>/anmelden/", views.register_event, name="register_event"),
    path("inhalte/", views.content_library, name="content_library"),
    path("inhalte/<int:article_id>/speichern/", views.save_content, name="save_content"),
    path("feedback/", views.feedback_center, name="feedback_center"),
    path("concierge/", views.concierge, name="concierge"),
    path("datenschutz-center/", views.privacy_center, name="privacy_center"),
    path("datenschutz-center/export/", views.request_export, name="request_export"),
    path("datenschutz-center/export/<int:export_id>/", views.download_export, name="download_export"),
    path("datenschutz-center/loeschen/", views.request_deletion, name="request_deletion"),
    path("datenschutz-center/geraet/<int:device_id>/", views.revoke_device, name="revoke_device"),
    path("push/subscribe/", views.push_subscribe, name="push_subscribe"),
    path("management-katalog/", views.management_catalog, name="management_catalog"),
    path("api/v1/modules/", views.api_modules, name="api_modules"),
    path("api/v1/dashboard/", views.api_dashboard, name="api_dashboard"),
    path("api/v1/slots/", views.api_slots, name="api_slots"),
    path("api/v1/wallet/", views.api_wallet, name="api_wallet"),
    path("api/v1/passport/", views.api_passport, name="api_passport"),
]
